POST {{baseUrl}}/api/auth/register
Content-Type: application/json

{
    "name": "TreinaWeb",
    "email": "contato@treinaweb.com.br",
    "password": "senha@123",
    "role": "COMPANY"
}

###

POST {{baseUrl}}/api/auth/login
Content-Type: application/json

{
    "email": "contato@treinaweb.com.br",
    "password": "senha@123"
}
