GET {{baseUrl}}/api/jobs

###

GET {{baseUrl}}/api/jobs/1

###

POST {{baseUrl}}/api/jobs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJjb250YXRvQHRyZWluYXdlYi5jb20uYnIiLCJpYXQiOjE3MDg2NTg3OTgsImV4cCI6MTcwODY2MjM5OH0.HBKDYaFOHyICKgzgPICWOUqFPqKWhsiSqXdkwyZTReYsqDFvbR94Wm02bPteyMELmYk3Ma3ixgNl6itHgZaEMg

{
    "title": "Desenvolvedor Java e Spring",
    "description": "Vaga para um  desenvolvedor Java e Spring",
    "location": "São Paulo",
    "level": "MID_LEVEL",
    "salary": 7500,
    "type": "FULL_TIME",
    "skills": [1, 2]
}

###

PUT {{baseUrl}}/api/jobs/4
Content-Type: application/json

{
    "title": "Desenvolvedor Back-end Java",
    "description": "Vaga para um desenvolvedor que saiba Java e Spring",
    "company": "TreinaWeb",
    "location": "São Paulo",
    "type": "FULL_TIME",
    "level": "SENIOR",
    "salary": 15000.00,
    "skills": [
        1, 
        2,
        10
    ]
}

###

DELETE {{baseUrl}}/api/jobs/3

###

GET {{baseUrl}}/api/jobs/2/skills
